version: "3.9"

services:
  web:
    build: .
    ports:
      - "8084:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: root123
      POSTGRES_DB: productos
      POSTGRES_USER: usuario_app
    ports:
      - "5432:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8085:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    depends_on:
      - db